version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: account-service-db
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: