name: Only Tests

on:
  push:
    branches-ignore:
      - master
      - main


jobs:
  run-all-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 4.0.0

      - name: All tests and coverages checks
        run: mvn clean install
